-
  name: installing localhost dependencies/aws sg/aws instance
  hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
    - /etc/ansible/cred.yml
  roles:
    - secgroup_instances

- name: configuring the servers instances
  hosts: webserver
  gather_facts: no
  tasks:
    - command: curl -4 icanhazip.com
      register: x
    - debug:
        var:  x.stdout
    - name: pass variables to role
      include_role:
        name: httpd
      vars:
        my_ip: x.stdout

- name: Creating and Configuring the load balancer
  hosts: localhost
  gather_facts: no
  vars_files:
    - /etc/ansible/cred.yml
  roles:
    - loadbalancer
